vars:
  BUNDLE_ID:
    default: calculator.tips.share
  PACKAGE_NAME:
    default: calculator.tips.share

platforms:
  ios:
    targets:
      App:
        incrementVersionCode: true
        bundleId: $BUNDLE_ID

        version: 16.4
        productName: Tips Share Calculator
        displayName: Tips Share

        buildSettings:
          ENABLE_BITCODE: false
          STRIP_SWIFT_SYMBOLS: false

        plist:
          replace: false
          entries:
            - NSFaceIDUsageDescription: Use Face ID to authenticate yourself and login

        entitlements:
          - keychain-access-groups:
              [
                'com.keychain.access.group'
              ]

        frameworks:
          - CoreServices.framework
          - ImageIO.framework
          - LocalAuthentication.framework
          - WebKit.framework
  android:
    incrementVersionCode: true
    packageName: $PACKAGE_NAME

    manifest:
      - file: android/app/src/main/AndroidManifest.xml
        target: manifest/application
        inject: <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

      - file: AndroidManifest.xml
        target: manifest/application
        attrs:
          android:name: $PACKAGE_NAME

      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <queries>
              <intent>
                  <action android:name="android.intent.action.MAIN" />
                  <category android:name="android.intent.category.LAUNCHER" />
              </intent>
          </queries>

    res:
      - path: raw
        file: config.json
        text: |
          {
            "value": true
          }
      - path: drawable
        file: icon.png
        source: ./resources/icon.png
